// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylzqjxfbtlkmlxdopita.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsenFqeGZidGxrbWx4ZG9waXRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxODg4NzMsImV4cCI6MjA0OTc2NDg3M30.wss0yUIXvDlDTx4EEB3C-RAGvKoqbSUOFOXM-bMupnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);