// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuibotqkltnxmhsljmlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1aWJvdHFrbHRueG1oc2xqbWxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0MTg2NDQsImV4cCI6MjA1NDk5NDY0NH0.s-awLoXAJz8pr5pb6jfCbe0CxI8RSomDS7_4S-EA9WI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);